---
- name: Actualizar apt cache y paquetes base
  ansible.builtin.apt:
    update_cache: true
    upgrade: safe
    cache_valid_time: 3600

- name: Instalar paquetes esenciales
  ansible.builtin.apt:
    name:
      - curl
      - wget
      - git
      - vim
      - htop
      - jq
      - yq
      - nfs-common
      - open-iscsi
      - python3-pip
      - ca-certificates
      - gnupg
      - lsb-release
    state: present

- name: Configurar hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Configurar timezone
  community.general.timezone:
    name: "{{ common_timezone }}"

- name: Habilitar cgroups para K3s (RPi)
  ansible.builtin.lineinfile:
    path: /boot/firmware/cmdline.txt
    backrefs: true
    regexp: '^((?!.*cgroup_enable).*)$'
    line: '\1 cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1'
  notify: Reiniciar sistema

- name: Configurar SSH hardening
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    mode: "0600"
  notify: Reiniciar SSH

- name: Configurar fail2ban
  ansible.builtin.apt:
    name: fail2ban
    state: present
