# TEMPLATE â€” sustituir APP_NAME, APP_PORT, APP_NAMESPACE
apiVersion: v1
kind: Service
metadata:
  name: APP_NAME
  namespace: APP_NAMESPACE
spec:
  selector:
    app: APP_NAME
  ports:
    - port: APP_PORT
      targetPort: APP_PORT
      protocol: TCP
