apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-negri-es
  namespace: traefik
spec:
  secretName: wildcard-negri-es-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "negri.es"
    - "*.negri.es"
  privateKey:
    algorithm: RSA
    size: 4096
