apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
  - helmrelease.yaml
  - middlewares.yaml
  - certificate-wildcard.yaml
configMapGenerator:
  - name: traefik-values
    files:
      - values.yaml
