roles:
  - name: geerlingguy.pip
    version: "2.2.0"
  - name: geerlingguy.docker
    version: "7.0.0"

collections:
  - name: community.general
    version: ">=8.0.0"
  - name: ansible.posix
    version: ">=1.5.0"
  - name: kubernetes.core
    version: ">=3.0.0"
